### PR TITLE
[done] Update 01.1-introduction.md

### PR DESCRIPTION
**Pull request by johav**
initial edits, tbc …
For the Glossary aka Jargon busting, should original definitions from mentioned sources be cited or paraphrased? (I'd suggest the latter as proposed for the Wikipedia references for Data Science and Reproducibility. Glossary changed to alphabetical order

<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

### CODE REVIEW

**Comment by johav** [comment]
Hey @arronlacey and @malvikasharan Would it be feasible to review the PRs thus far so we can incorporate progress?
I will continue working on the other episodes in the meantime. Getting feedback and being able to agree on some of the details raised in suggestions for changes would just make it easier to find a common voice moving forward quickly. 
Thx :)

**Review by malvikasharan — APPROVED** [review]
Thank you @johav. This looks good to me. 💐

**Review by malvikasharan — APPROVED** [review]

**Comment by arronlacey** [comment]
Hi @johav - I merged [johav-patch-4](https://github.com/carpentries-incubator/data-science-ai-senior-researchers/tree/johav-patch-4) into gh-pages which has the file `01.1-introduction.md` but in this branch you want to rename in to `00-Welcome.md`. Which one did you want to go with? [johav-patch-4](https://github.com/carpentries-incubator/data-science-ai-senior-researchers/tree/johav-patch-4) came after this branch so I wasn't sure.

**Comment by johav** [comment]
Hey @arronlacey thnx for this! I was suggesting naming the first episode "00 Welcome" as it does not yet contain educational content is serves more as a description and orientation for participants. And then starting with 01 onwards for the content episodes. What do you think? The numbering and taxonomy should best be consistent with other Carpentry courses.

**Review by malvikasharan — APPROVED** [review]
Looks good to me. Thank you for updating this. Can we merge this?

**Pull request merged**
